### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by m007** [threema-ch/threema-msgapi-sdk-java#3]
# Problem 
Information in the ```Readme``` file.

# How to find out
... (section just added to keep the layout used in #1 and #2) :wink: 

# How to fix
Update ```Readme```. Maybe add that a [maven](https://maven.apache.org) project can be found under the ```source``` folder (and probably that the ```.jar``` can be build using ```mvn clean package```).

**Comment by micwin** [comment]
I propose using markdown. I'm about to configure your site generation in the pom as well. Gimme some more minutes and we can discuss my proposal, ok?

**Comment by threema-ch** [comment]
make your merge request, we will check it. thank you.

**Comment by micwin** [comment]
Hmm, imho the proper approach would be to use github pages  in conjunction with the maven site plugin, but that's quite a bit of work.

As an example, see the difference on my ticino project. This is the githuib repository : 

- https://github.com/micwin/ticino - known layout and ugly
- http://micwin.github.io/ticino/ - github pages, also ugly (i like ugly web pages;) ), but more standard

To use github pages you have to activate it in the github repositoriy's admin console, and then put the html stuff on the branch gh-pages. Thats all.

**Comment by micwin** [comment]
Uah, too long. Short on the point: 

- Put all the documentation into markdown files, 
- put them into the right folder (src/site/markdown) 
- define menui items in your site.xml
- generate a site 
- put generated site onto github pages

sorry, my english sometimes makes me crazy.

grx mic

**Comment by m007** [comment]
Would apprciate this!

**Comment by micwin** [comment]
See pull request #10 . Someone has an idea on how to reference commits to isues so I can spare out those sort of comments? In JIRA, this is done by preceeding the commit comment with the ticket id, but this doesnt work here unfortunately,...

**Comment by micwin** [comment]
Referencing a ticket via commit message does, in fact, work. Sorry for the turbulence ;)
